functions:
- name: sub
  start: true
  type: NORMAL
  next:
    - switch1
- name: switch1
  type: SWITCH
  condition: input["subres"] < 0
  output:
    - subres
  next: 
    - reverse
    - times2
- name: reverse
  type: NORMAL
  next: 
    - times2
- name: times2
  type: NORMAL
  next: 
    - end
- name: end
  type: END
  output:
    - result

