functions:
- container: wasm
  name: cal
  next:
    funcs:
    - switch1
    - times2
    size: 12
    type: PASS
  runtime: 0.004914760589599609
  scale: 3
  source: cal
- container: wasm
  name: divide2
  next:
    funcs:
    - sum
    size: 4
    type: PASS
  runtime: 0.0055408477783203125
  scale: 3
  source: divide2
- container: wasm
  name: times2
  next:
    funcs:
    - sum
    size: 4
    type: PASS
  runtime: 0.012680768966674805
  scale: 3
  source: times2
- container: wasm
  name: switch1
  next:
    conditions:
    - subres < 0
    - default
    funcs:
    - reverse
    - sink
    size: 4
    type: SWITCH
  output:
  - subres
  runtime: 5.030632019042969e-05
  scale: 1
  source: SWITCH
- container: wasm
  name: reverse
  next:
    funcs:
    - sink
    size: 4
    type: PASS
  runtime: 0.010341882705688477
  scale: 3
  source: reverse
- container: wasm
  name: sink
  next:
    conditions:
    - default
    funcs:
    - sum
    size: 4
    type: SINK
  output:
  - subres
  runtime: 8.821487426757812e-06
  scale: 1
  source: SWITCH
- container: wasm
  name: sum
  next:
    funcs:
    - end
    size: 4
    type: PASS
  runtime: 0.014055252075195312
  scale: 3
  source: sum
- container: wasm
  name: end
  output:
  - input: DEFAULT
  runtime: 3.337860107421875e-06
  scale: 1
  source: END
wasmMode: INTERP
