functions:
- name: cal
  source: cal
  scale: 3
  runtime: 0.02
  next:
    type: PASS
    size: 8999999
    funcs:
      - switch1
      - times2
- name: divide2
  scale: 3
  source: divide2
  runtime: 0.01
  next:
    type: PASS
    size: 4999999
    funcs:
      - sum
- name: times2
  source: times2
  scale: 3
  runtime: 0.01
  next:
    type: PASS
    size: 4999999
    funcs:
      - sum
- name: switch1
  source: VIRTUAL
  scale: 3
  runtime: 0.01
  output:
      - subres
  next: 
    type: SWITCH
    size: 4999999
    conditions: 
      - subres < 0
      - default
    funcs:
      - reverse
      - sink
- name: reverse
  source: reverse
  scale: 3
  runtime: 0.01
  next: 
    type: PASS
    size: 4
    funcs:
      - sink
- name: sink
  source: VIRTUAL
  scale: 3
  runtime: 0.01
  output:
      - subres
  next: 
    type: SINK
    size: 4999999
    conditions: 
      - default
    funcs:
      - sum
- name: sum
  source: sum
  scale: 3
  runtime: 0.01
  next: 
    type: PASS
    size: 4999999
    funcs:
      - end
- name: end
  source: END
  scale: 3
  runtime: 0.01
  output:
    - input: DEFAULT

#  divide2---------------
#                       +
#  ------times2------->sum---> end
#  |                    +
#  |                    |                 
#  |             |--->sink<---
# cal-->switch1---           |
#                |           |
#                -------> reverse
#

 